import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import customAuthRouter from "./custom-auth";
import subjectsRouter from "./subjects";
import notesRouter from "./notes";
import quizRouter from "./quiz";
import gamesRouter from "./games";
import schedulesRouter from "./schedules";
import goalsRouter from "./goals";
import moodsRouter from "./moods";
import leaderboardRouter from "./leaderboard";
import achievementsRouter from "./achievements";
import shopRouter from "./shop";
import friendsRouter from "./friends";
import chatRouter from "./chat";
import usersRouter from "./users";
import curriculumQuizRouter from "./curriculum-quiz";
import developerRouter from "./developer";
import inboxRouter from "./inbox";
import powerupsRouter from "./powerups";
import reviewRouter from "./review";
import gradeChangeRouter from "./grade-change";
import storageRouter from "./storage";
import attachmentsRouter from "./attachments";
import streaksRouter from "./streaks";
import spinRouter from "./spin";
import mathBlitzRouter from "./math-blitz";
import chatbotRouter from "./chatbot";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(customAuthRouter);
router.use(developerRouter);
router.use(inboxRouter);
router.use(powerupsRouter);
router.use(reviewRouter);
router.use(gradeChangeRouter);
router.use(subjectsRouter);
router.use(notesRouter);
router.use(quizRouter);
router.use(gamesRouter);
router.use(schedulesRouter);
router.use(goalsRouter);
router.use(moodsRouter);
router.use(leaderboardRouter);
router.use(achievementsRouter);
router.use(shopRouter);
router.use(friendsRouter);
router.use(chatRouter);
router.use(usersRouter);
router.use(curriculumQuizRouter);
router.use(storageRouter);
router.use(attachmentsRouter);
router.use(streaksRouter);
router.use(spinRouter);
router.use(mathBlitzRouter);
router.use(chatbotRouter);

export default router;
